### ISSUE TITLE
Failing with rakudo versions that have unicode 11 support

### ISSUE THREAD

**Issue by AlexDaniel** [cygx/p6-unicode-gcb#1]
More info:
* Rakudo ticket: https://github.com/rakudo/rakudo/issues/2399
* IRC discussion: http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-10-20#l287

Basically, the code in this module has to be changed:

> 21:40:01 \<samcv\> they are using now discontinued GCB values hm
> 21:40:09 \<samcv\> err properties and such
> 21:40:17 \<samcv\> so that could have something to do with it
> 21:41:47 \<samcv\> MVM_UNICODE_PVALUE_GCB_E_BASE, MVM_UNICODE_PVALUE_GCB_E_BASE_GAZ, MVM_UNICODE_PVALUE_GCB_E_MODIFIER, MVM_UNICODE_PVALUE_GCB_GLUE_AFTER_ZWJ are not in unicode 11
> 22:17:12 \<samcv\> AlexDaniel: yeah so that program will have to be changed for Unicode 11 rules

Please note that ideally the code should be backward compatible for users who have older rakudo versions.

**Comment by cygx** [comment]
I've got a fix ready [in a branch](https://github.com/cygx/p6-unicode-gcb/tree/unicode11), but I still need to check that I didn't mess up (ideally by writing some tests ;))...

**Comment by cygx** [comment]
Resolved by 111df5f1a08c88460abcab602e7505538561f310
